import { IProduct } from "@/types/product.type";

const productsDemoData: IProduct[] = [
  {
    _id: "1",
    name: "মেকআপ কিট",
    description: "Complete makeup kit for professional use.",
    purchasePrice: 5000,
    regularPrice: 6000,
    salePrice: 5500,
    category: { _id: "c1", name: "Cosmetics" },
    brand: { _id: "b1", name: "BeautyPro" },
    tags: ["makeup", "kit", "cosmetics"],
    thumbnail:
      "https://demo.activeitzone.com/ecommerce_repo/public/uploads/all/mG4K0TiQAXxg1sOILVVyoNdECruuN5IvMufG9yWF.webp",
    gallery: [
      "https://demo.activeitzone.com/ecommerce_repo/public/uploads/all/mG4K0TiQAXxg1sOILVVyoNdECruuN5IvMufG9yWF.webp",
    ],
    stock: 100,
    sold: 320,
    isFeatured: true,
    ratings: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "2",
    name: "Coffee Jar",
    description: "Premium coffee jar with airtight seal.",
    purchasePrice: 9000,
    regularPrice: 10390,
    salePrice: 9990,
    category: { _id: "c2", name: "Kitchen" },
    brand: { _id: "b2", name: "CoffeeCo" },
    tags: ["coffee", "jar", "kitchen"],
    thumbnail:
      "https://demo.activeitzone.com/ecommerce_repo/public/uploads/all/vlH5gK4oe3IGl3BmfyCmrWew8w9FICzc7157BFiC.png",
    gallery: [
      "https://demo.activeitzone.com/ecommerce_repo/public/uploads/all/vlH5gK4oe3IGl3BmfyCmrWew8w9FICzc7157BFiC.png",
    ],
    stock: 80,
    sold: 210,
    isFeatured: false,
    ratings: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "3",
    name: "iPhone",
    description: "Latest iPhone model with high-end features.",
    purchasePrice: 16000,
    regularPrice: 17900,
    salePrice: 16900,
    category: { _id: "c1", name: "Electronics" },
    brand: { _id: "b3", name: "Apple" },
    tags: ["smartphone", "apple", "ios"],
    thumbnail:
      "https://demo.activeitzone.com/ecommerce_repo/public/uploads/all/B1hum7tEVbTF5SOV0eQdwB6NgyLUPO1wif5QtaO8.webp",
    gallery: [
      "https://demo.activeitzone.com/ecommerce_repo/public/uploads/all/B1hum7tEVbTF5SOV0eQdwB6NgyLUPO1wif5QtaO8.webp",
    ],
    stock: 200,
    sold: 1200,
    isFeatured: true,
    ratings: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "4",
    name: "Android Smartphone",
    description: "Affordable Android smartphone with good performance.",
    purchasePrice: 8500,
    regularPrice: 9900,
    salePrice: 9500,
    category: { _id: "c1", name: "Electronics" },
    brand: { _id: "b4", name: "Samsung" },
    tags: ["smartphone", "android"],
    thumbnail:
      "https://demo.activeitzone.com/ecommerce_repo/public/uploads/all/cJLH3YGg5OBTzgiDvMVE4Bw6d4jDM6l4gbTSCq4R.webp",
    gallery: [
      "https://demo.activeitzone.com/ecommerce_repo/public/uploads/all/cJLH3YGg5OBTzgiDvMVE4Bw6d4jDM6l4gbTSCq4R.webp",
    ],
    stock: 150,
    sold: 480,
    isFeatured: false,
    ratings: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "5",
    name: "Sweatshirt",
    description: "Comfortable and stylish sweatshirt.",
    purchasePrice: 4000,
    regularPrice: 5000,
    salePrice: 4500,
    category: { _id: "c3", name: "Fashion" },
    brand: { _id: "b5", name: "Clothify" },
    tags: ["sweatshirt", "fashion", "winter"],
    thumbnail:
      "https://demo.activeitzone.com/ecommerce_repo/public/uploads/all/jvVnqs9VFBp3LJy8iNxwYPFN6XZYnI3MlKogPkWv.webp",
    gallery: [
      "https://demo.activeitzone.com/ecommerce_repo/public/uploads/all/jvVnqs9VFBp3LJy8iNxwYPFN6XZYnI3MlKogPkWv.webp",
    ],
    stock: 90,
    sold: 760,
    isFeatured: true,
    ratings: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "6",
    name: "Pink Dress",
    description: "Elegant pink dress for parties and events.",
    purchasePrice: 4000,
    regularPrice: 4900,
    salePrice: 4500,
    category: { _id: "c3", name: "Fashion" },
    brand: { _id: "b6", name: "Fashionista" },
    tags: ["dress", "fashion", "party"],
    thumbnail:
      "https://demo.activeitzone.com/ecommerce_repo/public/uploads/all/mdNKoKdJXd2FZ38TgpgVI0OpWetrezEQSD6qNdKN.webp",
    gallery: [
      "https://demo.activeitzone.com/ecommerce_repo/public/uploads/all/mdNKoKdJXd2FZ38TgpgVI0OpWetrezEQSD6qNdKN.webp",
    ],
    stock: 70,
    sold: 530,
    isFeatured: true,
    ratings: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "7",
    name: "Tablet",
    description: "Lightweight tablet for browsing and media.",
    purchasePrice: 9000,
    regularPrice: 10000,
    salePrice: 9500,
    category: { _id: "c1", name: "Electronics" },
    brand: { _id: "b7", name: "TabCo" },
    tags: ["tablet", "electronics"],
    thumbnail:
      "https://demo.activeitzone.com/ecommerce_repo/public/uploads/all/cJLH3YGg5OBTzgiDvMVE4Bw6d4jDM6l4gbTSCq4R.webp",
    gallery: [
      "https://demo.activeitzone.com/ecommerce_repo/public/uploads/all/cJLH3YGg5OBTzgiDvMVE4Bw6d4jDM6l4gbTSCq4R.webp",
    ],
    stock: 80,
    sold: 610,
    isFeatured: false,
    ratings: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "8",
    name: "Gaming Console",
    description: "High-performance gaming console for gamers.",
    purchasePrice: 32000,
    regularPrice: 39000,
    salePrice: 35000,
    category: { _id: "c1", name: "Electronics" },
    brand: { _id: "b8", name: "GameBox" },
    tags: ["gaming", "console", "electronics"],
    thumbnail:
      "https://demo.activeitzone.com/ecommerce_repo/public/uploads/all/gC0Q2JfK6lG7CHedYEGcYJoutbDE4sWmHpBxmIqd.webp",
    gallery: [
      "https://demo.activeitzone.com/ecommerce_repo/public/uploads/all/gC0Q2JfK6lG7CHedYEGcYJoutbDE4sWmHpBxmIqd.webp",
    ],
    stock: 50,
    sold: 890,
    isFeatured: true,
    ratings: 5,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "9",
    name: "Hawaiian Shirt",
    description: "Casual Hawaiian shirt for summer vibes.",
    purchasePrice: 5000,
    regularPrice: 6000,
    salePrice: 5500,
    category: { _id: "c3", name: "Fashion" },
    brand: { _id: "b9", name: "SummerWear" },
    tags: ["shirt", "hawaiian", "fashion"],
    thumbnail:
      "https://demo.activeitzone.com/ecommerce_repo/public/uploads/all/70TVd2OrhelP4B9bqY9SIK3TnUpCtXkSLntYP5O4.webp",
    gallery: [
      "https://demo.activeitzone.com/ecommerce_repo/public/uploads/all/70TVd2OrhelP4B9bqY9SIK3TnUpCtXkSLntYP5O4.webp",
    ],
    stock: 70,
    sold: 420,
    isFeatured: false,
    ratings: 3,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "10",
    name: "Tablet Pro",
    description: "Advanced tablet with high-resolution display.",
    purchasePrice: 8000,
    regularPrice: 9000,
    salePrice: 8500,
    category: { _id: "c1", name: "Electronics" },
    brand: { _id: "b7", name: "TabCo" },
    tags: ["tablet", "electronics", "pro"],
    thumbnail:
      "https://demo.activeitzone.com/ecommerce_repo/public/uploads/all/yLwzQu7Cn0zfjXWmtFaIBGiEFB5d4lh0jF41LKZP.webp",
    gallery: [
      "https://demo.activeitzone.com/ecommerce_repo/public/uploads/all/yLwzQu7Cn0zfjXWmtFaIBGiEFB5d4lh0jF41LKZP.webp",
    ],
    stock: 60,
    sold: 350,
    isFeatured: true,
    ratings: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "11",
    name: "Tablet Pro",
    description: "Advanced tablet with high-resolution display.",
    purchasePrice: 8000,
    regularPrice: 9000,
    salePrice: 8500,
    category: { _id: "c1", name: "Electronics" },
    brand: { _id: "b7", name: "TabCo" },
    tags: ["tablet", "electronics", "pro"],
    thumbnail:
      "https://demo.activeitzone.com/ecommerce_repo/public/uploads/all/yLwzQu7Cn0zfjXWmtFaIBGiEFB5d4lh0jF41LKZP.webp",
    gallery: [
      "https://demo.activeitzone.com/ecommerce_repo/public/uploads/all/yLwzQu7Cn0zfjXWmtFaIBGiEFB5d4lh0jF41LKZP.webp",
    ],
    stock: 60,
    sold: 350,
    isFeatured: true,
    ratings: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "12",
    name: "Tablet Pro",
    description: "Advanced tablet with high-resolution display.",
    purchasePrice: 8000,
    regularPrice: 9000,
    salePrice: 8500,
    category: { _id: "c1", name: "Electronics" },
    brand: { _id: "b7", name: "TabCo" },
    tags: ["tablet", "electronics", "pro"],
    thumbnail:
      "https://demo.activeitzone.com/ecommerce_repo/public/uploads/all/yLwzQu7Cn0zfjXWmtFaIBGiEFB5d4lh0jF41LKZP.webp",
    gallery: [
      "https://demo.activeitzone.com/ecommerce_repo/public/uploads/all/yLwzQu7Cn0zfjXWmtFaIBGiEFB5d4lh0jF41LKZP.webp",
    ],
    stock: 60,
    sold: 350,
    isFeatured: true,
    ratings: 4,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export default productsDemoData;
