import { ICategory } from "@/types/category.type";

const CategoriesDemoData: ICategory[] = [
  {
    _id: "66e1f1000000000000000001",
    name: "Men's Clothing",
    slug: "mens-clothing",
    description: "Trendy and comfortable apparel for men.",
    image: "",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "66e1f1000000000000000002",
    name: "Women's Clothing",
    slug: "womens-clothing",
    description: "Fashionable wear for women of all styles.",
    image: "",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "66e1f1000000000000000003",
    name: "Kids Clothing",
    slug: "kids-clothing",
    description: "Cute and durable clothes for kids.",
    image: "",
    isFeatured: false,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "66e1f1000000000000000004",
    name: "Shoes",
    slug: "shoes",
    description: "Latest collections of shoes for all occasions.",
    image: "",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "66e1f1000000000000000005",
    name: "Bags & Accessories",
    slug: "bags-accessories",
    description: "Stylish bags, wallets, and fashion accessories.",
    image: "",
    isFeatured: false,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "66e1f1000000000000000006",
    name: "Watches",
    slug: "watches",
    description: "Premium and casual watches for all genders.",
    image: "",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "66e1f1000000000000000007",
    name: "Jewelry",
    slug: "jewelry",
    description: "Elegant jewelry pieces for special moments.",
    image: "",
    isFeatured: false,
    isPublished: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "66e1f1000000000000000008",
    name: "Beauty & Personal Care",
    slug: "beauty-personal-care",
    description: "Cosmetics, skincare, and grooming essentials.",
    image: "",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "66e1f1000000000000000009",
    name: "Health & Wellness",
    slug: "health-wellness",
    description: "Supplements, fitness, and wellness products.",
    image: "",
    isFeatured: false,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "66e1f100000000000000000a",
    name: "Home & Living",
    slug: "home-living",
    description: "Furniture, decor, and home essentials.",
    image: "",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "66e1f100000000000000000b",
    name: "Kitchen & Dining",
    slug: "kitchen-dining",
    description: "Cookware, utensils, and dining essentials.",
    image: "",
    isFeatured: false,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "66e1f100000000000000000c",
    name: "Electronics",
    slug: "electronics",
    description: "Latest gadgets and electronic devices.",
    image: "",
    isFeatured: true,
    isPublished: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "66e1f100000000000000000d",
    name: "Mobile Phones",
    slug: "mobile-phones",
    description: "Smartphones from top brands.",
    image: "",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "66e1f100000000000000000e",
    name: "Laptops",
    slug: "laptops",
    description: "Portable and powerful laptops for work and play.",
    image: "",
    isFeatured: true,
    isPublished: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "66e1f100000000000000000f",
    name: "Gaming",
    slug: "gaming",
    description: "Consoles, games, and accessories for gamers.",
    image: "",
    isFeatured: false,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "66e1f1000000000000000010",
    name: "Sports & Outdoors",
    slug: "sports-outdoors",
    description: "Sportswear, equipment, and outdoor essentials.",
    image: "",
    isFeatured: false,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "66e1f1000000000000000011",
    name: "Books & Stationery",
    slug: "books-stationery",
    description: "Books, journals, and office supplies.",
    image: "",
    isFeatured: false,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "66e1f1000000000000000012",
    name: "Toys & Games",
    slug: "toys-games",
    description: "Fun toys and games for kids and adults.",
    image: "",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "66e1f1000000000000000013",
    name: "Automotive",
    slug: "automotive",
    description: "Car accessories, tools, and spare parts.",
    image: "",
    isFeatured: false,
    isPublished: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: "66e1f1000000000000000014",
    name: "Pet Supplies",
    slug: "pet-supplies",
    description: "Food, toys, and care items for pets.",
    image: "",
    isFeatured: false,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export default CategoriesDemoData;
