export interface Product {
  id: number
  name: string
  image: string
  images?: string[] // Added multiple images for gallery
  rating: number
  reviewCount?: number // Added review count
  price: number
  originalPrice?: number // Added original price for discounts
  category: string
  subcategory: string
  brand: string
  inStock: boolean
  warranty?: string // Added warranty information
  isInhouseProduct?: boolean // Added inhouse product flag
  colors?: string[] // Added available colors
  description?: string // Added product description
  features?: string[] // Added product features
}

export const products: Product[] = [
  // Computer & Accessories
  {
    id: 1,
    name: "Canon EOS 5D MarkII",
    image: "/images/products/canon-dslr-camera.png",
    images: ["/images/products/canon-dslr-camera.png", "/images/products/canon-dslr-camera.png"],
    rating: 4,
    reviewCount: 12,
    price: 899,
    originalPrice: 999,
    category: "computer-accessories",
    subcategory: "desktop-pc",
    brand: "Canon",
    inStock: true,
    warranty: "2 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black", "silver"],
    description: "Professional DSLR camera with advanced features for photography enthusiasts.",
    features: ["24.1MP Full Frame CMOS Sensor", "DIGIC 4 Image Processor", "3.0-inch LCD Monitor"],
  },
  {
    id: 4,
    name: "Apple iPhone 14 128GB (Unlocked)",
    image: "/iphone-14-multiple-colors-display.png",
    images: ["/iphone-14-multiple-colors-display.png", "/iphone-14-side-view.png", "/product-thumbnail.png"],
    rating: 5,
    reviewCount: 8,
    price: 579000,
    originalPrice: 599000,
    category: "computer-accessories",
    subcategory: "laptops",
    brand: "Apple",
    inStock: false,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: true,
    colors: ["white", "black", "blue", "pink"],
    description:
      "The iPhone 14 is equipped with a 6.1-inch OLED display and Apple's improved Bionic A15 processor. On the back there is a Dual camera setup with 12MP main camera and 12MP Ultra-wide sensor.",
    features: ["6.1-inch OLED Display", "A15 Bionic Chip", "Dual Camera System", "Face ID"],
  },
  {
    id: 17,
    name: "Dell XPS 13 Laptop",
    image: "/images/products/dell-laptop.png",
    images: ["/images/products/dell-laptop.png"],
    rating: 4,
    reviewCount: 15,
    price: 1299,
    originalPrice: 1399,
    category: "computer-accessories",
    subcategory: "laptops",
    brand: "Dell",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["silver", "black"],
    description: "Ultra-portable laptop with premium build quality and excellent performance.",
    features: ["13.3-inch InfinityEdge Display", "Intel Core i7 Processor", "16GB RAM", "512GB SSD"],
  },
  {
    id: 18,
    name: "HP Gaming Desktop PC",
    image: "/images/products/hp-desktop.png",
    images: ["/images/products/hp-desktop.png"],
    rating: 4,
    reviewCount: 22,
    price: 899,
    originalPrice: 999,
    category: "computer-accessories",
    subcategory: "desktop-pc",
    brand: "HP",
    inStock: true,
    warranty: "2 Year Brand Warranty",
    isInhouseProduct: true,
    colors: ["black"],
    description: "High-performance gaming desktop with powerful graphics and fast processing.",
    features: ["AMD Ryzen 5 Processor", "NVIDIA GTX 1660 Graphics", "16GB DDR4 RAM", "1TB HDD + 256GB SSD"],
  },
  {
    id: 19,
    name: "ASUS ROG Gaming Motherboard",
    image: "/images/products/asus-motherboard.png",
    images: ["/images/products/asus-motherboard.png"],
    rating: 5,
    reviewCount: 18,
    price: 299,
    originalPrice: 349,
    category: "computer-accessories",
    subcategory: "motherboard",
    brand: "ASUS",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "High-performance gaming motherboard with advanced features for building powerful gaming PCs.",
    features: ["Intel Z690 Chipset", "16 Phase Digital VRM", "4 PCIe 4.0 Slots", "RGB Fusion 3.0"],
  },
  {
    id: 20,
    name: "Samsung 55 inch 4K Smart TV",
    image: "/images/products/samsung-tv.png",
    images: ["/images/products/samsung-tv.png"],
    rating: 5,
    reviewCount: 25,
    price: 799,
    originalPrice: 899,
    category: "computer-accessories",
    subcategory: "smart-tv",
    brand: "Samsung",
    inStock: true,
    warranty: "2 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Enjoy stunning 4K visuals with this Samsung Smart TV.",
    features: ["4K UHD Resolution", "HDR10+", "Smart TV with Tizen OS", "Built-in Alexa"],
  },
  {
    id: 45,
    name: "MacBook Air M2 13-inch",
    image: "/images/products/macbook-air-m2.png",
    images: ["/images/products/macbook-air-m2.png"],
    rating: 5,
    reviewCount: 30,
    price: 1199,
    originalPrice: 1299,
    category: "computer-accessories",
    subcategory: "laptops",
    brand: "Apple",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: true,
    colors: ["silver", "space gray"],
    description: "Lightweight and powerful laptop with M2 chip.",
    features: ["13.3-inch Liquid Retina Display", "M2 Chip", "8-core CPU", "8GB RAM"],
  },
  {
    id: 47,
    name: "AirPods Pro 2nd Generation",
    image: "/images/products/airpods-pro.png",
    images: ["/images/products/airpods-pro.png"],
    rating: 5,
    reviewCount: 20,
    price: 249,
    originalPrice: 299,
    category: "computer-accessories",
    subcategory: "headphones",
    brand: "Apple",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: true,
    colors: ["white"],
    description: "Noise-cancelling headphones with adaptive EQ.",
    features: ["Active Noise Cancellation", "Transparency Mode", "Adaptive EQ", "Touch Controls"],
  },
  {
    id: 48,
    name: "Samsung Galaxy Tab S9",
    image: "/images/products/galaxy-tab-s9.png",
    images: ["/images/products/galaxy-tab-s9.png"],
    rating: 4,
    reviewCount: 17,
    price: 799,
    originalPrice: 899,
    category: "cellphones-tabs",
    subcategory: "android-tablet",
    brand: "Samsung",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black", "white"],
    description: "Powerful Android tablet with S Pen support.",
    features: ["12.4-inch Super AMOLED Display", "Samsung Exynos 2200 Processor", "S Pen", "5G Connectivity"],
  },
  {
    id: 49,
    name: "Samsung 65 inch QLED 4K TV",
    image: "/images/products/samsung-qled-tv.png",
    images: ["/images/products/samsung-qled-tv.png"],
    rating: 5,
    reviewCount: 28,
    price: 1299,
    originalPrice: 1399,
    category: "computer-accessories",
    subcategory: "smart-tv",
    brand: "Samsung",
    inStock: true,
    warranty: "2 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Experience true-to-life colors with this Samsung QLED TV.",
    features: ["65-inch QLED Display", "4K UHD Resolution", "HDR10+", "Smart TV with Tizen OS"],
  },
  {
    id: 50,
    name: "Samsung Galaxy Buds Pro",
    image: "/images/products/galaxy-buds-pro.png",
    images: ["/images/products/galaxy-buds-pro.png"],
    rating: 4,
    reviewCount: 19,
    price: 199,
    originalPrice: 249,
    category: "computer-accessories",
    subcategory: "headphones",
    brand: "Samsung",
    inStock: false,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Wireless earbuds with active noise cancellation.",
    features: ["Active Noise Cancellation", "Touch Controls", "Water and Sweat Resistance", "Bluetooth 5.3"],
  },
  {
    id: 67,
    name: "Sony PlayStation 5 Console",
    image: "/images/products/playstation-5.png",
    images: ["/images/products/playstation-5.png"],
    rating: 5,
    reviewCount: 35,
    price: 499,
    originalPrice: 599,
    category: "computer-accessories",
    subcategory: "gaming-console",
    brand: "Sony",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["white"],
    description: "Next-generation gaming console with lightning-fast loading times.",
    features: ["825GHZ Custom SSD", "DualSense Wireless Controller", "Ray Tracing Support", "4K Resolution"],
  },
  {
    id: 68,
    name: "Sony WH-1000XM5 Headphones",
    image: "/images/products/sony-headphones.png",
    images: ["/images/products/sony-headphones.png"],
    rating: 5,
    reviewCount: 27,
    price: 399,
    originalPrice: 499,
    category: "computer-accessories",
    subcategory: "headphones",
    brand: "Sony",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Noise-cancelling headphones with advanced sound quality.",
    features: ["Active Noise Cancellation", "Adaptive Sound Control", "Touch Controls", "Bluetooth 5.2"],
  },
  {
    id: 69,
    name: "Sony Alpha A7 IV Camera",
    image: "/images/products/sony-camera.png",
    images: ["/images/products/sony-camera.png"],
    rating: 5,
    reviewCount: 24,
    price: 2499,
    originalPrice: 2699,
    category: "computer-accessories",
    subcategory: "digital-camera",
    brand: "Sony",
    inStock: true,
    warranty: "2 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Professional mirrorless camera with excellent low-light performance.",
    features: ["36.3MP Full Frame Sensor", "BIONZ X Image Processor", "4K Video Recording", "3.2-inch LCD Monitor"],
  },
  {
    id: 70,
    name: "Microsoft Surface Pro 9",
    image: "/images/products/surface-pro-9.png",
    images: ["/images/products/surface-pro-9.png"],
    rating: 4,
    reviewCount: 21,
    price: 1299,
    originalPrice: 1399,
    category: "computer-accessories",
    subcategory: "laptops",
    brand: "Microsoft",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: true,
    colors: ["silver", "black"],
    description: "Versatile laptop with stylus support and powerful performance.",
    features: ["13-inch PixelSense Display", "Intel Core i7 Processor", "16GB RAM", "512GB SSD"],
  },
  {
    id: 71,
    name: "Xbox Series X Console",
    image: "/images/products/xbox-series-x.png",
    images: ["/images/products/xbox-series-x.png"],
    rating: 5,
    reviewCount: 32,
    price: 499,
    originalPrice: 599,
    category: "computer-accessories",
    subcategory: "gaming-console",
    brand: "Microsoft",
    inStock: false,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "High-performance gaming console with ray tracing support.",
    features: ["825GHZ Custom SSD", "DualSense Wireless Controller", "Ray Tracing Support", "4K Resolution"],
  },

  // Home Decoration & Appliance
  {
    id: 2,
    name: "97 Inch Class LG OLED evo G4 4K Smart TV 2024 with Supplied",
    image: "/images/products/large-oled-tv-screen.png",
    images: ["/images/products/large-oled-tv-screen.png"],
    rating: 5,
    reviewCount: 29,
    price: 2999,
    originalPrice: 3199,
    category: "home-decoration-appliance",
    subcategory: "home-furniture",
    brand: "LG",
    inStock: true,
    warranty: "2 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Large OLED TV with stunning picture quality.",
    features: ["97-inch OLED Display", "4K UHD Resolution", "HDR10+", "Smart TV with WebOS"],
  },
  {
    id: 21,
    name: "Modern Leather Sofa Set",
    image: "/images/products/leather-sofa.png",
    images: ["/images/products/leather-sofa.png"],
    rating: 4,
    reviewCount: 16,
    price: 1299,
    originalPrice: 1399,
    category: "home-decoration-appliance",
    subcategory: "home-furniture",
    brand: "IKEA",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black", "gray"],
    description: "Comfortable and stylish leather sofa set.",
    features: ["Leather Upholstery", "Reclining Function", "Power Headrests", "Built-in Speakers"],
  },
  {
    id: 22,
    name: "Wooden Dining Table Set",
    image: "/images/products/dining-table.png",
    images: ["/images/products/dining-table.png"],
    rating: 4,
    reviewCount: 14,
    price: 699,
    originalPrice: 799,
    category: "home-decoration-appliance",
    subcategory: "home-furniture",
    brand: "West Elm",
    inStock: false,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["brown"],
    description: "Stylish wooden dining table set for your home.",
    features: ["Solid Wood Construction", "Extendable Design", "Modern Aesthetic", "Easy Assembly"],
  },

  // Men Clothing & Fashion
  {
    id: 3,
    name: "HOBIBEAR Unisex Garden Clogs Lightweight Slippers Sandals for Men",
    image: "/images/products/black-garden-clogs-sandals.png",
    images: ["/images/products/black-garden-clogs-sandals.png"],
    rating: 5,
    reviewCount: 45,
    price: 29,
    originalPrice: 39,
    category: "men-clothing",
    subcategory: "casual-shirts",
    brand: "HOBIBEAR",
    inStock: true,
    warranty: "6 Month Brand Warranty",
    isInhouseProduct: false,
    colors: ["black", "blue", "gray"],
    description: "Comfortable and lightweight garden clogs perfect for casual wear.",
    features: ["Lightweight EVA Material", "Non-slip Sole", "Easy to Clean", "Ventilation Holes"],
  },
  {
    id: 10,
    name: "Helly-Hansen Mens Crew Waterproof Windproof Breathable",
    image: "/images/products/gray-jacket-windbreaker.png",
    images: ["/images/products/gray-jacket-windbreaker.png"],
    rating: 5,
    reviewCount: 38,
    price: 89,
    originalPrice: 99,
    category: "men-clothing",
    subcategory: "leather-jackets",
    brand: "Helly-Hansen",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["gray"],
    description: "Waterproof and windproof jacket for outdoor activities.",
    features: ["Waterproof Material", "Windproof Design", "Breathable Ventilation", "Insulated Liner"],
  },
  {
    id: 11,
    name: "Fashion Sneakers, Lace-Up Or Slip-On Mens Casual Shoes",
    image: "/images/products/white-casual-sneakers.png",
    images: ["/images/products/white-casual-sneakers.png"],
    rating: 5,
    reviewCount: 26,
    price: 59,
    originalPrice: 69,
    category: "men-clothing",
    subcategory: "jeans",
    brand: "Nike",
    inStock: false,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["white"],
    description: "Comfortable and stylish casual sneakers.",
    features: ["Lightweight Construction", "Breathable Mesh Upper", "Foam Midsole", "Rubber Outsole"],
  },
  {
    id: 23,
    name: "Men's Cotton Casual T-Shirt",
    image: "/images/products/mens-tshirt.png",
    images: ["/images/products/mens-tshirt.png"],
    rating: 4,
    reviewCount: 19,
    price: 25,
    originalPrice: 35,
    category: "men-clothing",
    subcategory: "t-shirts",
    brand: "Uniqlo",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Comfortable cotton casual t-shirt.",
    features: ["Soft Cotton Fabric", "Regular Fit", "Machine Washable", "Stylish Design"],
  },
  {
    id: 24,
    name: "Men's Slim Fit Jeans",
    image: "/images/products/mens-jeans.png",
    images: ["/images/products/mens-jeans.png"],
    rating: 4,
    reviewCount: 23,
    price: 79,
    originalPrice: 89,
    category: "men-clothing",
    subcategory: "jeans",
    brand: "Levi's",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["blue"],
    description: "Slim fit jeans with a classic look.",
    features: ["Stretchable Denim", "Slim Fit", "Machine Washable", "Button Fly"],
  },
  {
    id: 52,
    name: "Nike Dri-FIT Training T-Shirt",
    image: "/images/products/nike-training-shirt.png",
    images: ["/images/products/nike-training-shirt.png"],
    rating: 4,
    reviewCount: 17,
    price: 35,
    originalPrice: 45,
    category: "men-clothing",
    subcategory: "t-shirts",
    brand: "Nike",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Breathable training t-shirt for workouts.",
    features: ["Dri-FIT Technology", "Quick-Dry Fabric", "Regular Fit", "Machine Washable"],
  },
  {
    id: 55,
    name: "Adidas Originals Hoodie",
    image: "/images/products/adidas-hoodie.png",
    images: ["/images/products/adidas-hoodie.png"],
    rating: 4,
    reviewCount: 21,
    price: 89,
    originalPrice: 99,
    category: "men-clothing",
    subcategory: "hoodies",
    brand: "Adidas",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Stylish hoodie with comfortable design.",
    features: ["Soft Fleece Material", "Hooded Design", "Regular Fit", "Machine Washable"],
  },
  {
    id: 74,
    name: "H&M Men's Casual Shirt",
    image: "/images/products/hm-mens-shirt.png",
    images: ["/images/products/hm-mens-shirt.png"],
    rating: 3,
    reviewCount: 15,
    price: 29,
    originalPrice: 39,
    category: "men-clothing",
    subcategory: "casual-shirts",
    brand: "H&M",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Casual shirt from H&M.",
    features: ["Soft Cotton Fabric", "Regular Fit", "Machine Washable", "Stylish Design"],
  },

  // Women Clothing & Fashion
  {
    id: 5,
    name: "Jessica Simpson Womens Setira Solid Slip-On Pumps",
    image: "/images/products/black-high-heel-pumps.png",
    images: ["/images/products/black-high-heel-pumps.png"],
    rating: 5,
    reviewCount: 22,
    price: 79,
    originalPrice: 89,
    category: "women-clothing",
    subcategory: "party-dress",
    brand: "Jessica Simpson",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Elegant slip-on pumps for special occasions.",
    features: ["Solid Leather Upper", "Comfortable Cushioning", "Stiletto Heel", "Easy to Wear"],
  },
  {
    id: 25,
    name: "Women's Elegant Evening Dress",
    image: "/images/products/evening-dress.png",
    images: ["/images/products/evening-dress.png"],
    rating: 5,
    reviewCount: 28,
    price: 149,
    originalPrice: 159,
    category: "women-clothing",
    subcategory: "party-dress",
    brand: "Zara",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Elegant evening dress for formal events.",
    features: ["Silk Fabric", "Fitted Design", "Long Sleeve", "Machine Washable"],
  },
  {
    id: 26,
    name: "Women's Casual Summer Dress",
    image: "/images/products/summer-dress.png",
    images: ["/images/products/summer-dress.png"],
    rating: 4,
    reviewCount: 19,
    price: 59,
    originalPrice: 69,
    category: "women-clothing",
    subcategory: "casual-dress",
    brand: "H&M",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["white"],
    description: "Casual summer dress for warm weather.",
    features: ["Cotton Fabric", "Flowy Design", "Short Sleeve", "Machine Washable"],
  },
  {
    id: 27,
    name: "Women's Designer Handbag",
    image: "/images/products/designer-handbag.png",
    images: ["/images/products/designer-handbag.png"],
    rating: 5,
    reviewCount: 24,
    price: 299,
    originalPrice: 349,
    category: "women-clothing",
    subcategory: "handbags",
    brand: "Coach",
    inStock: false,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Stylish designer handbag for everyday use.",
    features: ["Leather Construction", "Multiple Compartments", "Adjustable Strap", "Waterproof"],
  },
  {
    id: 53,
    name: "Nike Women's Yoga Leggings",
    image: "/images/products/nike-yoga-leggings.png",
    images: ["/images/products/nike-yoga-leggings.png"],
    rating: 5,
    reviewCount: 26,
    price: 79,
    originalPrice: 89,
    category: "women-clothing",
    subcategory: "activewear",
    brand: "Nike",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Comfortable yoga leggings for fitness enthusiasts.",
    features: ["Stretchable Fabric", "Four-Way Stretch", "Breathable Design", "Machine Washable"],
  },
  {
    id: 56,
    name: "Adidas Women's Sports Bra",
    image: "/images/products/adidas-sports-bra.png",
    images: ["/images/products/adidas-sports-bra.png"],
    rating: 4,
    reviewCount: 20,
    price: 45,
    originalPrice: 55,
    category: "women-clothing",
    subcategory: "activewear",
    brand: "Adidas",
    inStock: false,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Supportive sports bra for workouts.",
    features: ["Breathable Fabric", "High Support", "Quick-Dry Technology", "Machine Washable"],
  },
  {
    id: 72,
    name: "Zara Women's Blazer",
    image: "/images/products/zara-blazer.png",
    images: ["/images/products/zara-blazer.png"],
    rating: 4,
    reviewCount: 18,
    price: 89,
    originalPrice: 99,
    category: "women-clothing",
    subcategory: "blazers",
    brand: "Zara",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Stylish blazer for professional wear.",
    features: ["Soft Cotton Blend", "Fitted Design", "Long Sleeve", "Machine Washable"],
  },
  {
    id: 73,
    name: "Zara Women's Ankle Boots",
    image: "/images/products/zara-boots.png",
    images: ["/images/products/zara-boots.png"],
    rating: 4,
    reviewCount: 21,
    price: 79,
    originalPrice: 89,
    category: "women-clothing",
    subcategory: "boots",
    brand: "Zara",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Comfortable ankle boots for everyday wear.",
    features: ["Leather Upper", "Soft Cushioning", "Waterproof Design", "Machine Washable"],
  },
  {
    id: 75,
    name: "H&M Kids Colorful T-Shirt",
    image: "/images/products/hm-kids-tshirt.png",
    images: ["/images/products/hm-kids-tshirt.png"],
    rating: 4,
    reviewCount: 16,
    price: 15,
    originalPrice: 25,
    category: "kids-toy",
    subcategory: "baby-dresses",
    brand: "H&M",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["red", "blue", "green"],
    description: "Colorful t-shirt for kids.",
    features: ["Soft Cotton Fabric", "Regular Fit", "Machine Washable", "Stylish Design"],
  },

  // Jewelry & Watches
  {
    id: 6,
    name: "Gold Watches for Women with Gold Stainless Steel",
    image: "/images/products/gold-luxury-watch.png",
    images: ["/images/products/gold-luxury-watch.png"],
    rating: 5,
    reviewCount: 25,
    price: 199,
    originalPrice: 249,
    category: "jewelry-watches",
    subcategory: "smart-watch",
    brand: "Rolex",
    inStock: true,
    warranty: "2 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["gold"],
    description: "Luxury gold watch with stainless steel band.",
    features: ["Water Resistant", "Chronograph Function", "Stainless Steel Band", "Automatic Winding"],
  },
  {
    id: 7,
    name: "Fashion LED Digital Watch Outdoor 30M Waterproof Rubber",
    image: "/images/products/digital-sports-watch.png",
    images: ["/images/products/digital-sports-watch.png"],
    rating: 5,
    reviewCount: 22,
    price: 49,
    originalPrice: 59,
    category: "jewelry-watches",
    subcategory: "digital-watch",
    brand: "Samsung",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Digital watch with LED display and waterproof design.",
    features: ["LED Display", "Waterproof to 30M", "Sporty Design", "Battery Life up to 300 hours"],
  },
  {
    id: 8,
    name: "Bulova Mens Classic Sutton 3-Hand Calendar Date Quartz",
    image: "/images/products/mens-dress-watch.png",
    images: ["/images/products/mens-dress-watch.png"],
    rating: 5,
    reviewCount: 20,
    price: 149,
    originalPrice: 159,
    category: "jewelry-watches",
    subcategory: "mechanical-watch",
    brand: "Bulova",
    inStock: false,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Classic men's dress watch with a 3-hand calendar.",
    features: ["Quartz Movement", "3-Hand Calendar", "Stainless Steel Case", "Water Resistant"],
  },
  {
    id: 9,
    name: "Bulova Mens Modern Gold Tone Stainless Steel 3-Hand Calendar",
    image: "/images/products/black-luxury-watch.png",
    images: ["/images/products/black-luxury-watch.png"],
    rating: 4,
    reviewCount: 19,
    price: 299,
    originalPrice: 349,
    category: "jewelry-watches",
    subcategory: "sports-watch",
    brand: "Bulova",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["gold"],
    description: "Modern men's watch with gold tone and 3-hand calendar.",
    features: ["Quartz Movement", "3-Hand Calendar", "Stainless Steel Case", "Water Resistant"],
  },
  {
    id: 28,
    name: "Diamond Engagement Ring",
    image: "/images/products/diamond-ring.png",
    images: ["/images/products/diamond-ring.png"],
    rating: 5,
    reviewCount: 30,
    price: 2999,
    originalPrice: 3199,
    category: "jewelry-watches",
    subcategory: "engagement-rings",
    brand: "Tiffany",
    inStock: true,
    warranty: "2 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["white"],
    description: "Beautiful diamond engagement ring.",
    features: ["1 Carat Diamond", "White Gold Setting", "Stainless Steel Band", "Water Resistant"],
  },
  {
    id: 46,
    name: "Apple Watch Series 9",
    image: "/images/products/apple-watch-series9.png",
    images: ["/images/products/apple-watch-series9.png"],
    rating: 5,
    reviewCount: 27,
    price: 399,
    originalPrice: 449,
    category: "jewelry-watches",
    subcategory: "smart-watch",
    brand: "Apple",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: true,
    colors: ["black"],
    description: "Latest Apple smartwatch with advanced features.",
    features: ["Always-On Retina Display", "S6 Chip", "Water Resistant", "GPS"],
  },
  {
    id: 65,
    name: "Rolex Submariner - Luxury Dive Watch",
    image: "/images/products/rolex-submariner.png",
    images: ["/images/products/rolex-submariner.png"],
    rating: 5,
    reviewCount: 24,
    price: 8999,
    originalPrice: 9499,
    category: "jewelry-watches",
    subcategory: "mechanical-watch",
    brand: "Rolex",
    inStock: true,
    warranty: "2 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["gold"],
    description: "Luxury dive watch from Rolex.",
    features: ["Water Resistant to 100M", "Automatic Winding", "Stainless Steel Case", "Chronograph Function"],
  },
  {
    id: 66,
    name: "Rolex Daytona - Racing Chronograph",
    image: "/images/products/rolex-daytona.png",
    images: ["/images/products/rolex-daytona.png"],
    rating: 5,
    reviewCount: 22,
    price: 12999,
    originalPrice: 13499,
    category: "jewelry-watches",
    subcategory: "sports-watch",
    brand: "Rolex",
    inStock: false,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Racing chronograph watch from Rolex.",
    features: ["Chronograph Function", "Water Resistant", "Stainless Steel Case", "Automatic Winding"],
  },

  // Automobile & Motorcycle
  {
    id: 12,
    name: "Royal Enfield Motorcycle - Classic Design, Modern Performance",
    image: "/images/products/yellow-motorcycle-bike.png",
    images: ["/images/products/yellow-motorcycle-bike.png"],
    rating: 5,
    reviewCount: 28,
    price: 4999,
    originalPrice: 5499,
    category: "automobile-motorcycle",
    subcategory: "racing-bike",
    brand: "Royal Enfield",
    inStock: true,
    warranty: "2 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["yellow"],
    description: "Classic design motorcycle with modern performance.",
    features: ["350cc Engine", "Classic Design", "Powerful Performance", "Waterproof"],
  },
  {
    id: 16,
    name: "BMW 520d M Sport - Luxury Sedan with TwinPower Turbo",
    image: "/images/products/white-bmw-sedan-car.png",
    images: ["/images/products/white-bmw-sedan-car.png"],
    rating: 5,
    reviewCount: 32,
    price: 45999,
    originalPrice: 47999,
    category: "automobile-motorcycle",
    subcategory: "luxury-suv",
    brand: "BMW",
    inStock: true,
    warranty: "2 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["white"],
    description: "Luxury sedan with TwinPower Turbo engine.",
    features: ["3.0-liter Inline-6 Engine", "TwinPower Turbo", "Luxury Interior", "Advanced Safety Features"],
  },
  {
    id: 29,
    name: "Honda Civic - Reliable Compact Car",
    image: "/images/products/honda-civic.png",
    images: ["/images/products/honda-civic.png"],
    rating: 4,
    reviewCount: 25,
    price: 23999,
    originalPrice: 24999,
    category: "automobile-motorcycle",
    subcategory: "sedan-car",
    brand: "Honda",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["silver"],
    description: "Reliable compact car with excellent performance.",
    features: ["1.5-liter Inline-4 Engine", "Smooth Performance", "Compact Design", "Advanced Safety Features"],
  },
  {
    id: 30,
    name: "Toyota Camry Hybrid",
    image: "/images/products/toyota-camry.png",
    images: ["/images/products/toyota-camry.png"],
    rating: 5,
    reviewCount: 30,
    price: 28999,
    originalPrice: 30999,
    category: "automobile-motorcycle",
    subcategory: "sedan-car",
    brand: "Toyota",
    inStock: false,
    warranty: "2 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Hybrid sedan with excellent fuel efficiency.",
    features: ["2.5-liter Inline-4 Engine", "Hybrid Technology", "Smooth Performance", "Advanced Safety Features"],
  },
  {
    id: 57,
    name: "BMW X5 - Luxury SUV",
    image: "/images/products/bmw-x5.png",
    images: ["/images/products/bmw-x5.png"],
    rating: 5,
    reviewCount: 35,
    price: 65999,
    originalPrice: 67999,
    category: "automobile-motorcycle",
    subcategory: "luxury-suv",
    brand: "BMW",
    inStock: true,
    warranty: "2 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Luxury SUV with powerful performance.",
    features: ["3.0-liter Inline-6 Engine", "All-Wheel Drive", "Luxury Interior", "Advanced Safety Features"],
  },
  {
    id: 58,
    name: "BMW M3 - High Performance Sedan",
    image: "/images/products/bmw-m3.png",
    images: ["/images/products/bmw-m3.png"],
    rating: 5,
    reviewCount: 32,
    price: 72999,
    originalPrice: 74999,
    category: "automobile-motorcycle",
    subcategory: "sedan-car",
    brand: "BMW",
    inStock: false,
    warranty: "2 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "High-performance sedan with advanced features.",
    features: ["3.0-liter Inline-6 Engine", "Powerful Performance", "Luxury Interior", "Advanced Safety Features"],
  },
  {
    id: 59,
    name: "Toyota Prius - Hybrid Hatchback",
    image: "/images/products/toyota-prius.png",
    images: ["/images/products/toyota-prius.png"],
    rating: 4,
    reviewCount: 26,
    price: 27999,
    originalPrice: 28999,
    category: "automobile-motorcycle",
    subcategory: "sedan-car",
    brand: "Toyota",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["silver"],
    description: "Hybrid hatchback with excellent fuel efficiency.",
    features: ["1.8-liter Inline-4 Engine", "Hybrid Technology", "Compact Design", "Advanced Safety Features"],
  },
  {
    id: 60,
    name: "Toyota RAV4 - Compact SUV",
    image: "/images/products/toyota-rav4.png",
    images: ["/images/products/toyota-rav4.png"],
    rating: 5,
    reviewCount: 30,
    price: 32999,
    originalPrice: 33999,
    category: "automobile-motorcycle",
    subcategory: "luxury-suv",
    brand: "Toyota",
    inStock: true,
    warranty: "2 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Compact SUV with excellent off-road capabilities.",
    features: ["2.5-liter Inline-4 Engine", "All-Wheel Drive", "Compact Design", "Advanced Safety Features"],
  },
  {
    id: 61,
    name: "Ford Mustang - Sports Car",
    image: "/images/products/ford-mustang.png",
    images: ["/images/products/ford-mustang.png"],
    rating: 5,
    reviewCount: 28,
    price: 38999,
    originalPrice: 40999,
    category: "automobile-motorcycle",
    subcategory: "racing-bike",
    brand: "Ford",
    inStock: true,
    warranty: "2 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["red"],
    description: "Iconic sports car with powerful performance.",
    features: ["5.0-liter V8 Engine", "Powerful Performance", "Stylish Design", "Advanced Safety Features"],
  },
  {
    id: 62,
    name: "Ford F-150 - Pickup Truck",
    image: "/images/products/ford-f150.png",
    images: ["/images/products/ford-f150.png"],
    rating: 5,
    reviewCount: 32,
    price: 42999,
    originalPrice: 44999,
    category: "automobile-motorcycle",
    subcategory: "luxury-suv",
    brand: "Ford",
    inStock: true,
    warranty: "2 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Reliable pickup truck with powerful performance.",
    features: ["5.0-liter V8 Engine", "Powerful Performance", "Stylish Design", "Advanced Safety Features"],
  },

  // Kids & Toy
  {
    id: 13,
    name: "RoyalBaby Freestyle 5/7 Sport Kids Bike 12 14 16 18 20 Inch",
    image: "/images/products/kids-bicycle-bike.png",
    images: ["/images/products/kids-bicycle-bike.png"],
    rating: 5,
    reviewCount: 28,
    price: 129,
    originalPrice: 139,
    category: "kids-toy",
    subcategory: "baby-dresses",
    brand: "RoyalBaby",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["yellow"],
    description: "Sporty kids bike for outdoor adventures.",
    features: ["5/7 Speed Gear", "Adjustable Seat", "Waterproof", "Easy to Assemble"],
  },
  {
    id: 31,
    name: "Educational Building Blocks Set",
    image: "/images/products/building-blocks.png",
    images: ["/images/products/building-blocks.png"],
    rating: 5,
    reviewCount: 25,
    price: 39,
    originalPrice: 49,
    category: "kids-toy",
    subcategory: "educational-toys",
    brand: "LEGO",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["red"],
    description: "Educational building blocks set for kids.",
    features: ["Sturdy Blocks", "Creative Design", "Easy to Assemble", "Safe for Kids"],
  },
  {
    id: 32,
    name: "Kids Remote Control Car",
    image: "/images/products/rc-car.png",
    images: ["/images/products/rc-car.png"],
    rating: 4,
    reviewCount: 22,
    price: 79,
    originalPrice: 89,
    category: "kids-toy",
    subcategory: "educational-toys",
    brand: "Hot Wheels",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["red"],
    description: "Remote control car for kids to play with.",
    features: ["Realistic Design", "Smooth Movement", "Easy to Control", "Safe for Kids"],
  },
  {
    id: 63,
    name: "LEGO Creator Expert Modular Building",
    image: "/images/products/lego-modular.png",
    images: ["/images/products/lego-modular.png"],
    rating: 5,
    reviewCount: 27,
    price: 199,
    originalPrice: 209,
    category: "kids-toy",
    subcategory: "educational-toys",
    brand: "LEGO",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["red"],
    description: "Expert modular building set for kids.",
    features: ["Detailed Instructions", "Sturdy Pieces", "Creative Design", "Safe for Kids"],
  },
  {
    id: 64,
    name: "LEGO Technic Supercar",
    image: "/images/products/lego-technic.png",
    images: ["/images/products/lego-technic.png"],
    rating: 5,
    reviewCount: 24,
    price: 399,
    originalPrice: 409,
    category: "toy",
    subcategory: "educational-toys",
    brand: "LEGO",
    inStock: false,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["red"],
    description: "Technic Supercar set for kids.",
    features: ["Detailed Instructions", "Sturdy Pieces", "Creative Design", "Safe for Kids"],
  },

  // Sports & Outdoor
  {
    id: 14,
    name: "Huffy Stone Mountain Hardtail Mountain Bike for",
    image: "/images/products/mountain-bike-bicycle.png",
    images: ["/images/products/mountain-bike-bicycle.png"],
    rating: 4,
    reviewCount: 22,
    price: 199,
    originalPrice: 209,
    category: "sports-outdoor",
    subcategory: "bicycles",
    brand: "Huffy",
    inStock: false,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Mountain bike for outdoor adventures.",
    features: ["Hardtail Suspension", "Sturdy Frame", "Waterproof", "Easy to Assemble"],
  },
  {
    id: 33,
    name: "Professional Tennis Racket",
    image: "/images/products/tennis-racket.png",
    images: ["/images/products/tennis-racket.png"],
    rating: 5,
    reviewCount: 28,
    price: 149,
    originalPrice: 159,
    category: "sports-outdoor",
    subcategory: "running-shoes",
    brand: "Wilson",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Professional tennis racket for sports enthusiasts.",
    features: ["Lightweight Construction", "Powerful Striking Surface", "Comfortable Grip", "Machine Washable"],
  },
  {
    id: 34,
    name: "Camping Tent for 4 People",
    image: "/images/products/camping-tent.png",
    images: ["/images/products/camping-tent.png"],
    rating: 4,
    reviewCount: 25,
    price: 199,
    originalPrice: 209,
    category: "sports-outdoor",
    subcategory: "camping-equipment",
    brand: "Coleman",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Camping tent for 4 people.",
    features: ["Waterproof Design", "Easy Setup", "Comfortable Interior", "Safe for Camping"],
  },
  {
    id: 51,
    name: "Nike Air Max 270 Running Shoes",
    image: "/images/products/nike-air-max-270.png",
    images: ["/images/products/nike-air-max-270.png"],
    rating: 5,
    reviewCount: 30,
    price: 149,
    originalPrice: 159,
    category: "sports-outdoor",
    subcategory: "running-shoes",
    brand: "Nike",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Comfortable running shoes with Air Max cushioning.",
    features: ["Air Max Cushioning", "Lightweight Construction", "Breathable Material", "Machine Washable"],
  },
  {
    id: 54,
    name: "Adidas Ultraboost 22 Running Shoes",
    image: "/images/products/adidas-ultraboost.png",
    images: ["/images/products/adidas-ultraboost.png"],
    rating: 5,
    reviewCount: 28,
    price: 179,
    originalPrice: 189,
    category: "sports-outdoor",
    subcategory: "running-shoes",
    brand: "Adidas",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "High-performance running shoes with Ultraboost cushioning.",
    features: ["Ultraboost Cushioning", "Lightweight Construction", "Breathable Material", "Machine Washable"],
  },

  // Toy
  {
    id: 15,
    name: "Whoopi Perkins Acoustic Right Handed",
    image: "/images/products/acoustic-guitar.png",
    images: ["/images/products/acoustic-guitar.png"],
    rating: 4,
    reviewCount: 25,
    price: 299,
    originalPrice: 309,
    category: "toy",
    subcategory: "educational-toys",
    brand: "Whoopi",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Acoustic guitar for kids to learn music.",
    features: ["Acoustic Design", "Easy to Play", "Educational Value", "Safe for Kids"],
  },
  {
    id: 35,
    name: "Electronic Learning Tablet for Kids",
    image: "/images/products/kids-tablet.png",
    images: ["/images/products/kids-tablet.png"],
    rating: 4,
    reviewCount: 22,
    price: 89,
    originalPrice: 99,
    category: "toy",
    subcategory: "educational-toys",
    brand: "LeapFrog",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Electronic learning tablet for kids.",
    features: ["Educational Apps", "Touchscreen Display", "Portable Design", "Safe for Kids"],
  },

  // Beauty, Health & Hair
  {
    id: 39,
    name: "Professional Hair Dryer",
    image: "/images/products/hair-dryer.png",
    images: ["/images/products/hair-dryer.png"],
    rating: 4,
    reviewCount: 20,
    price: 89,
    originalPrice: 99,
    category: "beauty-health-hair",
    subcategory: "hair",
    brand: "Dyson",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Professional hair dryer with advanced features.",
    features: ["High-Speed Hot Air", "Cool Shot Function", "Lightweight Design", "Machine Washable"],
  },
  {
    id: 40,
    name: "Anti-Aging Face Cream",
    image: "/images/products/face-cream.png",
    images: ["/images/products/face-cream.png"],
    rating: 4,
    reviewCount: 18,
    price: 59,
    originalPrice: 69,
    category: "beauty-health-hair",
    subcategory: "skin",
    brand: "L'Oreal",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Anti-aging face cream for skin care.",
    features: ["Anti-Aging Ingredients", "Rich Moisturizer", "Non-Greasy Formula", "Machine Washable"],
  },

  // Home Improvement & Tools
  {
    id: 41,
    name: "LED Strip Lights 16ft",
    image: "/images/products/led-strip.png",
    images: ["/images/products/led-strip.png"],
    rating: 4,
    reviewCount: 19,
    price: 29,
    originalPrice: 39,
    category: "home-improvement-tools",
    subcategory: "led-strip",
    brand: "Philips",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "16-foot LED strip lights for home improvement.",
    features: ["Energy Efficient", "Easy to Install", "Waterproof Design", "Machine Washable"],
  },
  {
    id: 42,
    name: "Cordless Drill Set",
    image: "/images/products/drill-set.png",
    images: ["/images/products/drill-set.png"],
    rating: 5,
    reviewCount: 27,
    price: 129,
    originalPrice: 139,
    category: "home-improvement-tools",
    subcategory: "hand-tools",
    brand: "DeWalt",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Cordless drill set for home improvement projects.",
    features: ["18V Lithium-Ion Battery", "Variable Speed Control", "Compact Design", "Machine Washable"],
  },

  // Software
  {
    id: 43,
    name: "Microsoft Office 365 Subscription",
    image: "/images/products/office-365.png",
    images: ["/images/products/office-365.png"],
    rating: 5,
    reviewCount: 30,
    price: 99,
    originalPrice: 109,
    category: "software",
    subcategory: "ides",
    brand: "Microsoft",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: true,
    colors: ["black"],
    description: "Microsoft Office 365 subscription for productivity.",
    features: ["Word", "Excel", "PowerPoint", "OneDrive"],
  },
  {
    id: 44,
    name: "Adobe Creative Suite",
    image: "/images/products/adobe-creative.png",
    images: ["/images/products/adobe-creative.png"],
    rating: 5,
    reviewCount: 28,
    price: 299,
    originalPrice: 309,
    category: "software",
    subcategory: "design-software",
    brand: "Adobe",
    inStock: true,
    warranty: "1 Year Brand Warranty",
    isInhouseProduct: false,
    colors: ["black"],
    description: "Adobe Creative Suite for professional design.",
    features: ["Photoshop", "Illustrator", "InDesign", "Premiere Pro"],
  },
]

export interface Review {
  id: number
  productId: number
  userName: string
  userAvatar: string
  rating: number
  date: string
  comment: string
}

export const reviews: Review[] = [
  {
    id: 1,
    productId: 4,
    userName: "Sophie Miller",
    userAvatar: "/placeholder.svg?height=40&width=40",
    rating: 5,
    date: "09-11-2024",
    comment:
      "I've been using protein powders, and this one is by far the best. It mixes easily with water or almond milk, and there's no weird aftertaste like some others I've had. The chocolate flavor is rich and smooth, and it's perfect for post-workout shakes. I also love that it's made with organic ingredients and has no artificial sweeteners. It gives me the right amount of protein boost without upsetting my stomach, like other powders sometimes do. I've been using it daily and will continue to purchase it!",
  },
  {
    id: 2,
    productId: 4,
    userName: "Jhone",
    userAvatar: "/placeholder.svg?height=40&width=40",
    rating: 5,
    date: "09-11-2024",
    comment: "Nice",
  },
  {
    id: 3,
    productId: 4,
    userName: "Charlotte",
    userAvatar: "/placeholder.svg?height=40&width=40",
    rating: 4,
    date: "09-11-2024",
    comment: "Very Nice",
  },
]
